---
# Basics
- hosts: all
  become: true
  roles:
    - bearandgiraffe.base
    - bearandgiraffe.ruby
    - {
      role:           bearandgiraffe.vim,
      vim_username:   '{{ username }}',
      vim_group_name: '{{ group_name }}'
    }
    - bearandgiraffe.node
    - bearandgiraffe.phantomjs
    - bearandgiraffe.php

# DB
- hosts: all
  become: true
  roles:
    - {
      role:              bearandgiraffe.mysql,
      mysql_db_name:     '{{ db_name }}',
      mysql_db_user:     '{{ db_user }}',
      mysql_db_password: '{{ db_password }}'
    }

- hosts: all
  user: vagrant
  tasks:
    - name: Ramove Apache2
      apt: name={{ item }} state=absent purge=yes force=yes
      with_items:
        - apache2
        - apache2-utils
      become: true

    - file: path=~

# Servers
- hosts: all
  become: true
  roles:
    - {
      role:               bearandgiraffe.nginx,
      nginx_home_path:    '{{ path }}',
      nginx_db_user:      '{{ db_user }}',
      nginx_db_password:  '{{ db_password }}',
      nginx_server_type:  '{{ server_type }}'
    }

# Wordpress
- hosts: all
  become: true
  roles:
    - wp
